---
- name: apiserver systemd service
  ansible.builtin.template:
    src: kube_apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
- name: start apiserver
  ansible.builtin.systemd:
    name: kube-apiserver
    state: restarted
    daemon_reload: true
    enabled: true