---
- name: scheduler systemd service
  ansible.builtin.template:
    src: kube_scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
- name: start scheduler
  ansible.builtin.systemd:
    name: kube-scheduler
    state: restarted
    enabled: true
    daemon_reload: true