- name: 检查 zhenshu 目录是否存在
  delegate_to: localhost
  stat:
    path: "{{ artifacts_dir }}/certs/"
  register: kubernetes_dir

- name: if certs not exists,create it and spread certs
  block: 
    - name: 运行任务 task.yml
      include_tasks: task.yml
      when: inventory_hostname in groups['master_bootstrap'] 
    - name: spread certs to all hosts
      synchronize:
        src: "{{ artifacts_dir }}/certs/"
        dest: /
        mode: push
  when: not kubernetes_dir.stat.exists
