cluster:
  children:
    master:
      children:
        master_bootstrap:
          hosts:
            10.60.81.77:
        master_add:
          hosts:
            10.60.210.214:
            10.60.37.50:
    node_add:
      hosts:
        10.60.184.148:
        10.60.117.250:
        10.60.170.78:
localhost:
  ansible_connection: local