cluster:
  children:
    master:
      children:
        master_bootstrap:
          hosts:
            10.7.141.190:
        master_add:
          hosts:
            10.7.4.11:
            10.7.25.125:
    node_add:
      hosts:
        10.7.119.91:
        10.7.172.45:
        10.7.38.122:
localhost:
  ansible_connection: local
