cluster:
  children:
    master:
      children:
        master_bootstrap:
          hosts:
            10.7.62.130:
        master_add:
          hosts:
            10.7.123.134:
            10.7.150.44:
    node_add:
      hosts:
        10.7.106.110:
        10.7.186.239:
        10.7.56.231:
localhost:
  ansible_connection: local
