---
- name: Check network connectivity
  block:
    - name: Attempt to ping xiong03.cn
      command: ping -c 3 xiong03.cn
      register: ping_result
      failed_when: false 
      changed_when: false
    - name: Update group network status if any host fails
      run_once: true  # 只在一台主机上执行
      delegate_to: localhost
      set_fact:
        all_hosts_network_ok: false
      when: "hostvars[item].ping_result.rc != 0"
      loop: "{{ ansible_play_hosts }}"  # 遍历所有主机
      loop_control:
        label: "{{ item }}"
    - name: quit if network is unreachable
      run_once: true
      delegate_to: localhost
      fail: 
        msg: "Network is unreachable for one or more hosts. Please check your network connection."
      when: not all_hosts_network_ok

- name: install necessary packages
  block:
  - name: Ensure apt cache is updated
    ansible.builtin.apt:
      update_cache: yes
    
  - name: Install necessary packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
    loop:
      - ntpdate
      - ca-certificates 
      - curl 
      - gnupg

- name: Synchronize time with NTP server
  ansible.builtin.command: ntpdate ntp.aliyun.com

- name: set timezone to Asia/Shanghai
  ansible.builtin.command: timedatectl set-timezone Asia/Shanghai

- name: enable modules
  ansible.builtin.copy:
    mode: "0644"
    dest: /etc/modules-load.d/kubernetes.conf
    content: |
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      nf_conntrack
      ip_tables
      ip_set
      xt_set
      ipt_set
      ipt_rpfilter
      ipt_REJECT
      ipip
      nf_conntrack
      br_netfilter
- name: restart systemd-modules-load.service
  ansible.builtin.systemd:
    name: systemd-modules-load.service
    state: restarted

- name: enable kernel parameters
  ansible.builtin.copy:
    mode: "0644"
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      fs.may_detach_mounts = 1
      vm.overcommit_memory=1
      vm.panic_on_oom=0
      fs.inotify.max_user_watches=89100
      fs.file-max=52706963
      fs.nr_open=52706963
      net.netfilter.nf_conntrack_max=2310720

      net.ipv4.tcp_keepalive_time = 600
      net.ipv4.tcp_keepalive_probes = 3
      net.ipv4.tcp_keepalive_intvl =15
      net.ipv4.tcp_max_tw_buckets = 36000
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.tcp_max_orphans = 327680
      net.ipv4.tcp_orphan_retries = 3
      net.ipv4.tcp_syncookies = 1
      net.ipv4.tcp_max_syn_backlog = 16384
      net.ipv4.ip_conntrack_max = 65536
      net.ipv4.tcp_max_syn_backlog = 16384
      net.ipv4.tcp_timestamps = 0
      net.core.somaxconn = 16384

      net.ipv6.conf.all.disable_ipv6 = 0
      net.ipv6.conf.default.disable_ipv6 = 0
      net.ipv6.conf.lo.disable_ipv6 = 0
      net.ipv6.conf.all.forwarding = 1
- name: sysctl --system
  ansible.builtin.command: sysctl --system

