---
- name: mkdir /etc/apt/keyrings to keep Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
- name: trust the Docker GPG key
  become: true
  block: 
  - ansible.builtin.shell: |
      curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg |  sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg 
      sudo chmod a+r /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  ansible.builtin.shell: |
    mkdir /etc/apt/sources.list.d/ -p && \
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
- name: Ensure Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
