# ---
# - name: common tasks
#   hosts: cluster
#   roles:
#     - common

- name: install runtime
  hosts: cluster
  tasks: 
    - name: install docker
      include_role:
        name: docker
      when:  ( enable_docker | bool ) or (enable_docker is not defined)

    - name: install containerd
      include_role:
        name: containerd
      when: not enable_docker | bool